Repository 2020PB/police-brutality, pull requests merged in 2020-10, with the labels that each got.

#1772 Update Arkansas.md
  reports/Arkansas.md
Labels: Incident Update

#1771 Update Arizona.md
  reports/Arizona.md
Labels: Incident Update

#1774 Update California.md
  reports/California.md
  reports/Washington.md
  tools/data_builder.py
Labels: Incident Update

#1781 Update Oregon.md
  reports/Oregon.md
  reports/Texas.md
Labels: New report

#1790 Update Washington.md
  reports/Washington.md
Labels: New report

#1787 Update California.md
  reports/California.md
Labels: Incident Update

#1793 Update Oregon.md
  reports/Oregon.md
Labels: New report

#1795 Update Connecticut.md
  reports/Connecticut.md
Labels: Incident Update

#1794 Update Colorado.md
  reports/Colorado.md
Labels: Incident Update

#1796 Update Delaware.md
  reports/Delaware.md
Labels: Incident Update

#1797 Update Florida.md
  reports/Florida.md
Labels: Incident Update

#1800 Update New York.md
  reports/New York.md
Labels: New report

#1801 Update Florida.md
  reports/Florida.md
Labels: Incident Update

#1807 Update Georgia.md
  reports/Georgia.md
Labels: Incident Update

#1808 Update Illinois.md
  reports/Illinois.md
Labels: Incident Update

#1814 Update Wisconsin.md
  reports/Wisconsin.md
Labels: New report

#1812 Update Illinois.md
  reports/Illinois.md
Labels: Incident Update

#1813 Update Indiana.md
  reports/Indiana.md
Labels: Incident Update

#1816 Update Wisconsin.md
  reports/Wisconsin.md
Labels: New report

#1819 Update Kansas.md
  reports/Kansas.md
Labels: Incident Update

#1818 Update Iowa.md
  reports/Iowa.md
Labels: Incident Update

#1821 Update Oregon.md
  reports/Oregon.md
Labels: New report

#1822 Update Arizona.md
  reports/Arizona.md
Labels: New report

#1826 Update Washington.md
  reports/Washington.md
Labels: Incident Update

#1825 Update New York.md
  reports/New York.md
Labels: Incident Update

#1832 Update Texas.md
  reports/Texas.md
Labels: New report

#1828 Update Texas.md
  reports/Texas.md
Labels: Incident Update

#1831 Update Michigan.md
  reports/Michigan.md
Labels: Incident Update

#1835 Update Washington DC.md
  reports/Texas.md
  reports/Washington DC.md
Labels: Incident Update

#1847 Update Ohio.md
  reports/Ohio.md
Labels: New report

#1844 Update Minnesota.md
  reports/Minnesota.md
Labels: Incident Update

#1850 Update Oregon.md
  reports/Oregon.md
Labels: Incident Update

#1851 Update Virginia.md
  reports/Virginia.md
Labels: Incident Update

#1852 Update New York.md
  reports/New York.md
Labels: Incident Update, New report

#1853 Update Kentucky.md
  reports/Kentucky.md
Labels: Incident Update

#1854 Update Nevada.md
  reports/Nevada.md
Labels: Incident Update

#1855 Update Washington.md
  reports/Washington.md
Labels: Incident Update

#1857 Update North Carolina.md
  reports/North Carolina.md
Labels: Incident Update

#1859 Update Michigan.md
  reports/Michigan.md
Labels: Incident Update

#1861 Update Pennsylvania.md
  reports/Pennsylvania.md
Labels: Incident Update

#1865 Update Ohio.md
  reports/Ohio.md
Labels: Incident Update

#1866 Update Texas.md
  reports/Texas.md
Labels: Incident Update

#1867 Update Arizona.md
  reports/Arizona.md
Labels: Incident Update

#1868 Update Wisconsin.md
  reports/Wisconsin.md
Labels: New report

#1869 Update California.md
  reports/California.md
Labels: New report

#1870 Update Oregon.md
  reports/Oregon.md
Labels: New report

#1872 Update Colorado.md
  reports/Colorado.md
Labels: New report

#1871 Update Florida.md
  reports/Florida.md
Labels: New report

#1873 Update Washington DC.md
  reports/Washington DC.md
Labels: New report

#1875 Update Wisconsin.md
  reports/Wisconsin.md
Labels: New report

#1883 Update Oregon.md
  reports/Oregon.md
Labels: New report

#1882 Update Georgia.md
  reports/Georgia.md
Labels: New report

#1884 Update Washington.md
  reports/Washington.md
Labels: New report

#1885 Update Oregon.md
  reports/Oregon.md
Labels: Incident Update

#1886 Added website link to README
  README.md
Labels: Docs

#1890 Update Kentucky.md
  reports/Kentucky.md
Labels: Incident Update

#1889 Update Oregon.md
  reports/Oregon.md
Labels: Incident Update, New report

#1891 Update Louisiana.md
  reports/Louisiana.md
Labels: Incident Update

#1892 Update Kentucky.md
  reports/Kentucky.md
Labels: Incident Update

#1897 Update Massachusetts.md
  reports/Massachusetts.md
Labels: Incident Update, New report

#1899 Update Michigan.md
  reports/Michigan.md
Labels: Incident Update

#1903 Update Rhode Island.md
  reports/Rhode Island.md
Labels: Incident Update, New report

#1904 Update Oregon.md
  reports/Oregon.md
Labels: New report

#1905 Update Michigan.md
  reports/Michigan.md
Labels: Incident Update

#1906 Update Minnesota.md
  reports/Minnesota.md
Labels: Incident Update

#1912 Update New York.md
  reports/New York.md
Labels: New report

#1909 Update Nebraska.md
  reports/Nebraska.md
Labels: Incident Update

#1908 Update Missouri.md
  reports/Missouri.md
Labels: Incident Update

#1913 Update Wisconsin.md
  reports/Wisconsin.md
Labels: New report

#1915 Update Nevada.md
  reports/Nevada.md
Labels: Incident Update

#1916 Update New Mexico.md
  reports/New Mexico.md
Labels: Incident Update

#1918 Update New York.md
  reports/New York.md
Labels: Incident Update

#1933 Update Washington DC.md
  reports/Washington DC.md
Labels: New report

#1930 Update Pennsylvania.md
  reports/Pennsylvania.md
Labels: Incident Update, New report

#1931 Update New York.md
  reports/New York.md
Labels: New report

#1940 Update Pennsylvania.md
  reports/Pennsylvania.md
Labels: Incident Update

#1942 Update New York.md
  reports/New York.md
Labels: Incident Update

#1943 Update Washington DC.md
  reports/Washington DC.md
Labels: New report

#1947 Update Pennsylvania.md
  reports/Pennsylvania.md
Labels: Incident Update

#1946 Update New York.md
  reports/New York.md
Labels: Incident Update
